description: "[ICRA 2023](https://www.icra2023.org/) workshop proposal <br/>  29 <sup>th</sup> May or 2<sup>nd</sup> June 2023 (tentative) <br/>  ExCeL London & online"
theme: jekyll-theme-cayman
title: "Life-Long Learning with Human Help (L<sup>3</sup> H<sup>2</sup> )"
